### PR TITLE
Require bombs to leave Hi Jump Lobby Missile

### PR DESCRIPTION
**Pull request by CPColin**
This technically changes the logic a tiny bit, so maybe we should wait until the next version? I set the version number to 9.8.1, in anticipation of that conclusion.

### CODE REVIEW

**Comment by MattEqualsCoder** [comment]
I'd actually argue it would make more sense as 9.8.0 since it's a larger release. You should update the randomizer version number though. (Assuming that still actually works as expected
 Lol)

**Comment by CPColin** [comment]
Yeah, that one test that makes sure the seed still works the same didn't break, probably because the seed it generates didn't care about this change haha. But I'll update the version, because yeah, it *is* a logic change, after all. Hopefully the current BCU async also doesn't care.

**Review by MattEqualsCoder — APPROVED** [review]
If you can, it might not be a bad idea to upload the build and post it to the dev channel to see if anyone who has played the async can pull it up and make sure that the in game code and the spoiler logs match.

**Comment by CPColin** [comment]
Generated the June async with both 9.7.4 and the code is this branch and the spoiler logs matched perfectly, aside from minor copy differences with the hints, which I'll file separately as a "might as well" kind of task.

**Pull request merged**
